version: '3.8'

services:
  db:
    image: postgres:15
    container_name: arritech_db
    restart: always
    environment:
      POSTGRES_USER: arritechappuser
      POSTGRES_PASSWORD: arritech_2025
      POSTGRES_DB: arritech_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - arritech-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: arritech_api
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8085:8080"
    networks:
      - arritech-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: arritech_frontend
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "5173:80"       # open http://localhost:5173
    networks:
      - arritech-network

volumes:
  pgdata:

networks:
  arritech-network: